version: '3.4'

services:
  socketiowithoutdb:
    image: socketiowithoutdb:v3
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: 10404
    ports:
      - 10404:10404
