version: '3'

services:
  socketiowithoutdb:
    image: socketiowithoutdb:v5
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: 10404
    ports:
      - 10404:10404
