version: '3.4'

services:
  socketiowithoutdb:
    image: socketiowithoutdb:v1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 10404:10404
